Vagrant.configure("2") do |config|
  config.vm.define "prod" do |vm_config|
    vm_config.vm.box = "generic/ubuntu2204"
    vm_config.vm.network "private_network", ip: "192.168.56.10"
    vm_config.vm.hostname = "prod"

    vm_config.vm.provider "virtualbox" do |vb|
      vb.name = "prod"
      vb.cpus = 2
      vb.memory = "2048"
    end

    # Run shell commands
    vm_config.vm.provision "shell", inline: <<-SHELL
      # Set password for root account and allow SSH
      echo "root:123" | chpasswd
      sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      # Append the following content to /etc/hosts for accessing machines by HOSTNAME
      cat >>/etc/hosts<<EOF
      192.168.56.10 prod
      192.168.56.11 stag
      192.168.56.12 dev
EOF

    SHELL

    # Run install-k8s.sh after provisioning the Box
    vm_config.vm.provision "shell", path: "./install-k8s.sh"
  end
end