Vagrant.configure("2") do |config|
    config.vm.define "k8s.master.pong" do |vm_config|
      vm_config.vm.box = "generic/ubuntu2204"
      vm_config.vm.network "private_network", ip: "192.168.56.100"
      vm_config.vm.hostname = "k8s.master.pong"
    
      vm_config.vm.provider "virtualbox" do |vb|
        vb.name = "k8s.master.pong"
        vb.cpus = 2
        vb.memory = "2048"
      end
      
      # Chạy file install-docker-kube.sh sau khi nạp Box
      vm_config.vm.provision "shell", path: "./../install-docker-kube.sh"
      
      # Chạy các lệnh shell
      vm_config.vm.provision "shell", inline: <<-SHELL
        # Đặt pass 123 cho tài khoản root và cho phép SSH
        echo "root:123" | chpasswd
        sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl reload sshd
  
        # Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
        cat >>/etc/hosts<<EOF
        192.168.56.100 k8s.master.pong
        192.168.56.101 k8s.worker1.pong
        192.168.56.102 k8s.worker2.pong
        EOF
        # Đặt DEBIAN_FRONTEND thành noninteractive để tránh lỗi dpkg-preconfigure
        export DEBIAN_FRONTEND=noninteractive
      SHELL
    end
  end  